version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    target-branch: develop      
    labels:
      - "kind/dependency-update"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - "kind/dependency-update"
    commit-message:
      prefix: "chore"
      include: "scope"