extends:
  - '@commitlint/config-conventional'

rules:
  scope-enum:
    - 2
    - always
    - [rightsizer, helm, docs, ci, deps]
  
  subject-max-length:
    - 2
    - always
    - 72

  body-max-line-length:
    - 2
    - always
    - 100