version: 2

project_name: k8s-rightsizer

before:
  hooks:
    - go mod tidy

builds:
  - id: k8s-rightsizer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/main.go
    binary: k8s-rightsizer

dockers:
  - id: k8s-rightsizer-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
    extra_files:
      - dist/k8s-rightsizer_linux_amd64_v1/k8s-rightsizer

  - id: k8s-rightsizer-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
    extra_files:
      - dist/k8s-rightsizer_linux_arm64/k8s-rightsizer

docker_manifests:
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-arm64

  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:latest
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-arm64

changelog:
  use: github

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: k8s-rightsizer
  draft: false
  prerelease: auto