# .goreleaser.yaml
version: 2

project_name: k8s-rightsizer

before:
  hooks:
    - go mod tidy

dockers:
  - id: k8s-rightsizer-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer

  - id: k8s-rightsizer-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer

docker_manifests:
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-arm64

  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:latest
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k8s-rightsizer:{{ .Tag }}-arm64

changelog:
  use: github

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: k8s-rightsizer
  release_notes_file: CHANGELOG.md
  draft: false
  prerelease: auto