image:
  pullPolicy: IfNotPresent
  
# Recommendations configuration
recommendations:
  pvcName: "recommendations-data-pvc" # The PVC where you upload the files
  fileName: "recommendations.xlsx"
  mountPath: "/data"

settings:
  resizeOnRecreate: false # Allow resizing if the workload update strategy is Recreate (default: false)
  dryRun: false # Enable dry-run mode (default: false)

rbac:
  create: true