image:
  pullPolicy: IfNotPresent
  
# Recommendations configuration
recommendations:
  pvcName: "recommendations-data-pvc" # The PVC where you upload the files
  fileName: "recommendations.xlsx"
  mountPath: "/data"

settings:
  resizeOnRecreate: false # Allow resizing if the workload update strategy is Recreate (default: false)
  dryRun: false # Enable dry-run mode (default: false)
  workers: 1 # Number of concurrent workers for processing recommendations (default: 1)
  resizeStrategy: "workload" # Resize strategy to use (default: workload, options: container, workload)
  useLimits: false # Use resource limits to set limits on containers (default: false)
  logLevel: "info" # Log level (default: info)
  postRolloutCheck: false # Enable post-rollout check (default: false)
  postRolloutCheckSec: 30 # Post-rollout check interval in seconds (default: 30)
  nodeCompatibilityCheckWindow: 90 # Node compatibility check window in days (default: 90)

rbac:
  create: true