image:
  repository: docker-registry/rightsizer #todo changeme
  pullPolicy: always
  tag: "latest"

storage:
  create: true # If the cluster has dynamic provisioning, you might set this to false and create only the PVC
  size: 1Gi
  accessMode: ReadWriteMany
  storageClass: "standard" # Or "longhorn", "azurefile", "efs-sc".
  hostPath: "" # Not used in remote environments
