apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-rightsizer-helm.fullname" . }}-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    checksum/config: {{ include (print $.Template.BasePath "/storage.yaml") . | sha256sum }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "k8s-rightsizer-helm.fullname" . }}
    spec:
      {{- if .Values.recommendations.git.enabled }}
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
          - "-c"
          - |
            echo "Checking out recommendations from Git..."
            git clone --depth=1 --branch {{ .Values.recommendations.git.branch }} {{ .Values.recommendations.git.repository }} /tmp/git-repo
            cp /tmp/git-repo/{{ .Values.recommendations.git.fileSourcePath }} {{ .Values.recommendations.mountPath }}/{{ .Values.recommendations.fileName }}
            echo "File successfully copied to {{ .Values.recommendations.mountPath }}/{{ .Values.recommendations.fileName }}"
        volumeMounts:
        - name: recommendations-storage
          mountPath: {{ .Values.recommendations.mountPath }}
      {{- end }}
      serviceAccountName: {{ include "k8s-rightsizer-helm.fullname" . }}
      containers:
      - name: rightsizer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: 
          - "--file-path"
          - "{{ .Values.recommendations.mountPath }}/{{ .Values.recommendations.fileName }}"
        volumeMounts:
        - name: recommendations-storage
          mountPath: {{ .Values.recommendations.mountPath }}
      volumes:
      - name: recommendations-storage
        persistentVolumeClaim:
          claimName: {{ .Values.recommendations.pvcName }}
      restartPolicy: OnFailure
  backoffLimit: 1