image:
  repository: localhost/k8s-rightsizer
  # For local development, we can set the pull policy to Never to use the locally built image
  pullPolicy: Never 
  tag: "local"

storage:
  create: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: manual
  # Path within the minikube node. 
  # Note: You must have run 'minikube mount /your/pc/data:/mnt/data'
  hostPath: "/mnt/data"


