name: Release Docker Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    name: Production Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Set up Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version: '1.26'
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/k8s-rightsizer:${{ steps.github.ref_name }}'
          format: 'table'
          exit-code: '1' # fail if critical or high vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
